name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-linux
          - aarch64-linux
          - x86_64-macos
          - aarch64-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build for ${{ matrix.target }}
        run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseSafe

      - name: Create artifact directory
        run: mkdir -p release

      - name: Package binary
        run: |
          mkdir -p mizar
          cp zig-out/bin/mizar mizar/
          tar -czf mizar-${{ matrix.target }}.tar.gz mizar
          mkdir -p release
          mv mizar-${{ matrix.target }}.tar.gz release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mizar-${{ matrix.target }}
          path: release/*.tar.gz

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}